/**
 * @theodoor/core — public barrel.
 *
 * NOTE FOR MODULE AGENTS: do not edit this file; export through your own
 * directory's index.ts. The integration owner wires new sub-barrels here.
 */
export * from './contracts.js'
export * from './math/index.js'
export * from './time/index.js'
export * from './text/index.js'
export * from './music/index.js'
export * from './music/analysis/index.js'
export * from './catalog/index.js'
export * from './site/index.js'
export * from './safety/index.js'
export * from './acoustics/index.js'
export * from './choreo/index.js'
export * from './transport/index.js'
export * from './export/index.js'
export * from './fab/index.js'
export * from './show/index.js'
export * from './sim/index.js'
export * from './gallery/index.js'
