/**
 * starter/beams.ts — steerable directional-audio programs ("audio
 * spotlights"), performance metadata only.
 *
 * noiseDbAt15m here is the AUDIBLE in-beam on-axis level at the reference
 * distance (<= 100 by catalog rule); out-of-beam listeners get far less, so
 * every entry is 'low-noise' plus the 'beam' tag. carrierBandLabel is an
 * opaque band name and maxCarrierDbAtFocus drives the exposure report.
 */

import type { BeamEffect } from '../../contracts.js'

export const BEAM_EFFECTS: readonly BeamEffect[] = [
  {
    id: 'beam-whisper-narration',
    name: 'Whisper Zone Narration',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'message'],
    noiseDbAt15m: 66,
    durationSec: 12,
    program: 'whisperZone',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 104,
    contentTag: 'narration',
  },
  {
    id: 'beam-flyover-whoosh',
    name: 'Flyover Whoosh',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'motion'],
    noiseDbAt15m: 74,
    durationSec: 6,
    program: 'flyover',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 108,
    contentTag: 'whoosh',
  },
  {
    id: 'beam-stereo-bed',
    name: 'Stereo Pair Bed',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'music'],
    noiseDbAt15m: 70,
    durationSec: 16,
    program: 'stereoPair',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 106,
    contentTag: 'stereo-bed',
  },
  {
    id: 'beam-pingpong-blip',
    name: 'Ping-Pong Blip',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'accent'],
    noiseDbAt15m: 72,
    durationSec: 8,
    program: 'pingPong',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 106,
    contentTag: 'blip',
  },
  {
    id: 'beam-tag-drone',
    name: 'Drone Source Tag',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'motion'],
    noiseDbAt15m: 70,
    durationSec: 12,
    program: 'sourceTag',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 106,
    contentTag: 'tag',
  },
  {
    id: 'beam-zone-pulse',
    name: 'Zone Pulse',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'accent'],
    noiseDbAt15m: 74,
    durationSec: 4,
    program: 'zonePulse',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 107,
    contentTag: 'pulse',
  },
  {
    id: 'beam-sweep-line',
    name: 'Sweep Line',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'motion'],
    noiseDbAt15m: 72,
    durationSec: 6,
    program: 'sweepLine',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 106,
    contentTag: 'sweep',
  },
  {
    id: 'beam-whisper-count',
    name: 'Whisper Count-In',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'countdown'],
    noiseDbAt15m: 64,
    durationSec: 10,
    program: 'whisperZone',
    beamWidthDeg: 6,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 104,
    contentTag: 'count-in',
  },
  {
    id: 'beam-toll-bell',
    name: 'Tolling Bell',
    medium: 'beam',
    tags: ['low-noise', 'beam', 'midnight'],
    noiseDbAt15m: 76,
    durationSec: 3,
    program: 'zonePulse',
    beamWidthDeg: 10,
    carrierBandLabel: 'u-band-40',
    maxCarrierDbAtFocus: 108,
    contentTag: 'bell',
  },
]
