/**
 * starter/crowd.ts — audience-device patterns (LED wristbands / phone
 * flashlights as a "crowd canvas" over the audience cell grid).
 *
 * These emit no sound of their own; noiseDbAt15m is pinned at 40 (the catalog
 * floor) and every entry carries 'low-noise' plus the 'crowd' tag. Colors are
 * CSS hex strings; hapticPulse is non-visual, so its color list is empty.
 * maskUpdateHz is the broadcast mask refresh rate the pattern consumes.
 */

import type { CrowdEffect } from '../../contracts.js'

export const CROWD_EFFECTS: readonly CrowdEffect[] = [
  {
    id: 'crowd-flood-rgb',
    name: 'Full Crowd Flood',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'calm'],
    noiseDbAt15m: 40,
    durationSec: 8,
    pattern: 'flood',
    channel: 'wristband',
    maskUpdateHz: 2,
    colors: ['#ff2a2a', '#2aff5e', '#2a6bff'],
  },
  {
    id: 'crowd-wave-lateral',
    name: 'Lateral Crowd Wave',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'blue'],
    noiseDbAt15m: 40,
    durationSec: 10,
    pattern: 'wave',
    channel: 'wristband',
    maskUpdateHz: 10,
    colors: ['#2266ff', '#66ccff'],
  },
  {
    id: 'crowd-pulse-radial',
    name: 'Radial Crowd Pulse',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'accent'],
    noiseDbAt15m: 40,
    durationSec: 6,
    pattern: 'radialPulse',
    channel: 'wristband',
    maskUpdateHz: 10,
    colors: ['#ffffff', '#ffd24d'],
  },
  {
    id: 'crowd-chase-sections',
    name: 'Section Chase',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'gold'],
    noiseDbAt15m: 40,
    durationSec: 12,
    pattern: 'sectionChase',
    channel: 'wristband',
    maskUpdateHz: 12,
    colors: ['#ffcc44', '#ff7a1a'],
  },
  {
    id: 'crowd-sparkle-gold',
    name: 'Gold Crowd Sparkle',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'gold', 'ambient'],
    noiseDbAt15m: 40,
    durationSec: 12,
    pattern: 'sparkle',
    channel: 'wristband',
    maskUpdateHz: 15,
    colors: ['#ffd27a', '#fff2c8'],
  },
  {
    id: 'crowd-text-marquee',
    name: 'Crowd Text Marquee',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'message'],
    noiseDbAt15m: 40,
    durationSec: 16,
    pattern: 'text',
    channel: 'wristband',
    maskUpdateHz: 20,
    colors: ['#ffffff'],
  },
  {
    id: 'crowd-heartbeat-red',
    name: 'Red Heartbeat',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'red', 'romance'],
    noiseDbAt15m: 40,
    durationSec: 8,
    pattern: 'heartbeat',
    channel: 'wristband',
    maskUpdateHz: 4,
    colors: ['#ff2a2a'],
  },
  {
    id: 'crowd-starfield-phone',
    name: 'Phone Flashlight Starfield',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'white', 'ambient'],
    noiseDbAt15m: 40,
    durationSec: 20,
    pattern: 'flashlightStarfield',
    channel: 'phone',
    maskUpdateHz: 6,
    colors: ['#ffffff'],
  },
  {
    id: 'crowd-haptic-thump',
    name: 'Haptic Thump',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'accent'],
    noiseDbAt15m: 40,
    durationSec: 4,
    pattern: 'hapticPulse',
    channel: 'wristband',
    maskUpdateHz: 4,
    colors: [],
  },
  {
    id: 'crowd-blackout',
    name: 'Crowd Blackout',
    medium: 'crowd',
    tags: ['low-noise', 'crowd', 'transition'],
    noiseDbAt15m: 40,
    durationSec: 4,
    pattern: 'flood',
    channel: 'wristband',
    maskUpdateHz: 2,
    colors: ['#000000'],
  },
]
