/**
 * starter/drones.ts — drone formation primitives, one per DroneFormationKind.
 *
 * Drones are near-silent (55–65 dB at 15 m) so every entry carries the
 * 'low-noise' tag. Per-cue params (count, scaleM, holdSec, text, rgb) refine
 * these at cue time; scaleM here is the default footprint.
 */

import type { DronePrimitive } from '../../contracts.js'

export const DRONE_EFFECTS: readonly DronePrimitive[] = [
  {
    id: 'grid-formation-100',
    name: 'Grid Matrix',
    medium: 'drone',
    tags: ['low-noise', 'calm'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'grid',
    minDrones: 25,
    maxDrones: 400,
    scaleM: 60,
  },
  {
    id: 'ring-formation-60',
    name: 'Halo Ring',
    medium: 'drone',
    tags: ['low-noise', 'classic'],
    noiseDbAt15m: 58,
    durationSec: 10,
    formation: 'ring',
    minDrones: 24,
    maxDrones: 240,
    scaleM: 50,
  },
  {
    id: 'star-formation-80',
    name: 'Five-Point Star',
    medium: 'drone',
    tags: ['low-noise', 'gold', 'celebration'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'star',
    minDrones: 40,
    maxDrones: 200,
    scaleM: 45,
  },
  {
    id: 'heart-formation-80',
    name: 'Sky Heart',
    medium: 'drone',
    tags: ['low-noise', 'red', 'romance'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'heart',
    minDrones: 40,
    maxDrones: 200,
    scaleM: 40,
  },
  {
    id: 'flag-formation-50',
    name: 'Waving Flag',
    medium: 'drone',
    tags: ['low-noise', 'red', 'white', 'blue', 'july4'],
    noiseDbAt15m: 62,
    durationSec: 15,
    formation: 'flag',
    minDrones: 50,
    maxDrones: 300,
    scaleM: 50,
  },
  {
    id: 'wave-formation-100',
    name: 'Rolling Wave',
    medium: 'drone',
    tags: ['low-noise', 'blue', 'calm'],
    noiseDbAt15m: 60,
    durationSec: 14,
    formation: 'wave',
    minDrones: 30,
    maxDrones: 300,
    scaleM: 80,
  },
  {
    id: 'text-formation-150',
    name: 'Sky Text',
    medium: 'drone',
    tags: ['low-noise', 'message'],
    noiseDbAt15m: 62,
    durationSec: 12,
    formation: 'text',
    minDrones: 60,
    maxDrones: 400,
    scaleM: 70,
  },
  {
    id: 'digit-formation-100',
    name: 'Countdown Digit',
    medium: 'drone',
    tags: ['low-noise', 'nye', 'countdown'],
    noiseDbAt15m: 60,
    durationSec: 8,
    formation: 'digit',
    minDrones: 40,
    maxDrones: 300,
    scaleM: 50,
  },
  {
    id: 'scatter-formation-100',
    name: 'Firefly Scatter',
    medium: 'drone',
    tags: ['low-noise', 'ambient'],
    noiseDbAt15m: 58,
    durationSec: 10,
    formation: 'scatter',
    minDrones: 20,
    maxDrones: 500,
    scaleM: 90,
  },
  {
    id: 'bloom-formation-120',
    name: 'Radial Bloom',
    medium: 'drone',
    tags: ['low-noise', 'gold', 'finale'],
    noiseDbAt15m: 60,
    durationSec: 8,
    formation: 'bloom',
    minDrones: 40,
    maxDrones: 300,
    scaleM: 60,
  },
  {
    id: 'clock-ring-formation-100',
    name: 'Midnight Clock Ring',
    medium: 'drone',
    tags: ['low-noise', 'nye', 'midnight'],
    noiseDbAt15m: 60,
    durationSec: 60,
    formation: 'clockRing',
    minDrones: 60,
    maxDrones: 240,
    scaleM: 55,
  },

  // ---- appended entries (append-only: golden fixtures depend on order) -----
  {
    id: 'bat-formation-80',
    name: 'Bat Silhouette',
    medium: 'drone',
    tags: ['low-noise', 'halloween'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'bat',
    minDrones: 40,
    maxDrones: 160,
    scaleM: 40,
  },
  {
    id: 'ghost-formation-60',
    name: 'Drifting Ghost',
    medium: 'drone',
    tags: ['low-noise', 'halloween'],
    noiseDbAt15m: 58,
    durationSec: 20,
    formation: 'ghost',
    minDrones: 30,
    maxDrones: 120,
    scaleM: 30,
  },
  {
    id: 'spiral-formation-120',
    name: 'Rising Spiral',
    medium: 'drone',
    tags: ['low-noise', 'abstract'],
    noiseDbAt15m: 60,
    durationSec: 14,
    formation: 'spiral',
    minDrones: 60,
    maxDrones: 300,
    scaleM: 70,
  },
  {
    id: 'cometTail-formation-90',
    name: 'Comet Tail Streak',
    medium: 'drone',
    tags: ['low-noise', 'gold', 'motion'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'cometTail',
    minDrones: 40,
    maxDrones: 200,
    scaleM: 50,
  },
  {
    id: 'saucer-formation-70',
    name: 'Flying Saucer',
    medium: 'drone',
    tags: ['low-noise', 'halloween'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'saucer',
    minDrones: 40,
    maxDrones: 160,
    scaleM: 35,
  },
  {
    id: 'orrery-formation-140',
    name: 'Planetary Orrery',
    medium: 'drone',
    tags: ['low-noise', 'calm'],
    noiseDbAt15m: 62,
    durationSec: 60,
    formation: 'orrery',
    minDrones: 80,
    maxDrones: 300,
    scaleM: 65,
  },
  {
    id: 'crescent-formation-60',
    name: 'Crescent Moon',
    medium: 'drone',
    tags: ['low-noise', 'calm', 'ambient'],
    noiseDbAt15m: 58,
    durationSec: 14,
    formation: 'crescent',
    minDrones: 30,
    maxDrones: 150,
    scaleM: 35,
  },
  {
    id: 'snowflake-formation-90',
    name: 'Snowflake Crystal',
    medium: 'drone',
    tags: ['low-noise', 'white', 'winter'],
    noiseDbAt15m: 60,
    durationSec: 12,
    formation: 'snowflake',
    minDrones: 40,
    maxDrones: 240,
    scaleM: 45,
  },
]
