/**
 * starter/panels.ts — LED panel patterns, one per PanelPatternKind.
 *
 * Panels are near-silent (fan noise only) — all 'low-noise'. fps is the
 * pattern's native frame rate; the sim renders and caches frames at it.
 */

import type { PanelPattern } from '../../contracts.js'

export const PANEL_EFFECTS: readonly PanelPattern[] = [
  {
    id: 'panel-solid-wash',
    name: 'Solid Color Wash',
    medium: 'panel',
    tags: ['low-noise', 'calm'],
    noiseDbAt15m: 55,
    durationSec: 8,
    pattern: 'solid',
    fps: 5,
  },
  {
    id: 'panel-gradient-wipe',
    name: 'Gradient Wipe',
    medium: 'panel',
    tags: ['low-noise', 'transition'],
    noiseDbAt15m: 55,
    durationSec: 6,
    pattern: 'gradientWipe',
    fps: 30,
  },
  {
    id: 'panel-sparkle',
    name: 'Sparkle Field',
    medium: 'panel',
    tags: ['low-noise', 'silver', 'ambient'],
    noiseDbAt15m: 55,
    durationSec: 10,
    pattern: 'sparkle',
    fps: 24,
  },
  {
    id: 'panel-flag-stripes',
    name: 'Flag Stripes',
    medium: 'panel',
    tags: ['low-noise', 'red', 'white', 'blue', 'july4'],
    noiseDbAt15m: 56,
    durationSec: 12,
    pattern: 'flagStripes',
    fps: 15,
  },
  {
    id: 'panel-waveform-bars',
    name: 'Waveform Bars',
    medium: 'panel',
    tags: ['low-noise', 'music'],
    noiseDbAt15m: 56,
    durationSec: 16,
    pattern: 'waveformBars',
    fps: 30,
  },
  {
    id: 'panel-text-marquee',
    name: 'Text Marquee',
    medium: 'panel',
    tags: ['low-noise', 'message'],
    noiseDbAt15m: 55,
    durationSec: 12,
    pattern: 'text',
    fps: 20,
  },
  {
    id: 'panel-strobe',
    name: 'Strobe Burst',
    medium: 'panel',
    tags: ['low-noise', 'white', 'accent'],
    noiseDbAt15m: 56,
    durationSec: 2,
    pattern: 'strobe',
    fps: 12,
  },
  {
    id: 'panel-chase',
    name: 'Chase Lights',
    medium: 'panel',
    tags: ['low-noise', 'gold', 'ambient'],
    noiseDbAt15m: 55,
    durationSec: 8,
    pattern: 'chase',
    fps: 30,
  },
  {
    id: 'panel-fireworks-echo',
    name: 'Fireworks Echo',
    medium: 'panel',
    tags: ['low-noise', 'finale'],
    noiseDbAt15m: 56,
    durationSec: 10,
    pattern: 'fireworks',
    fps: 30,
  },

  // ---- appended entries (append-only: golden fixtures depend on order) -----
  {
    id: 'panel-embers',
    name: 'Glowing Embers',
    medium: 'panel',
    tags: ['low-noise', 'gold', 'ambient'],
    noiseDbAt15m: 55,
    durationSec: 12,
    pattern: 'embers',
    fps: 30,
  },
  {
    id: 'panel-starfield',
    name: 'Starfield Drift',
    medium: 'panel',
    tags: ['low-noise', 'white', 'ambient'],
    noiseDbAt15m: 55,
    durationSec: 12,
    pattern: 'starfield',
    fps: 24,
  },
  {
    id: 'panel-aurora',
    name: 'Aurora Ribbons',
    medium: 'panel',
    tags: ['low-noise', 'green', 'calm'],
    noiseDbAt15m: 55,
    durationSec: 14,
    pattern: 'aurora',
    fps: 30,
  },
  {
    id: 'panel-lightning',
    name: 'Lightning Flash',
    medium: 'panel',
    tags: ['low-noise', 'white', 'accent'],
    noiseDbAt15m: 56,
    durationSec: 1.5,
    pattern: 'lightning',
    fps: 12,
  },
  {
    id: 'panel-eyes',
    name: 'Watching Eyes',
    medium: 'panel',
    tags: ['low-noise', 'halloween'],
    noiseDbAt15m: 55,
    durationSec: 10,
    pattern: 'eyes',
    fps: 10,
  },
]
