/**
 * starter/pyro.ts — pyro effect entries: performance metadata ONLY.
 *
 * Every field here describes what the audience sees and hears (timing,
 * geometry, colors, loudness) — never how anything is made. Colors are CSS
 * hex strings the sim/viz parse into rgb.
 *
 * Caliber → performance conventions used throughout:
 *   75 mm  ≈ 2.2 s rise,  ~90 m burst height, ~35 m radius
 *   100 mm ≈ 2.8 s rise, ~120 m burst height, ~45 m radius
 *   150 mm ≈ 3.6 s rise, ~170 m burst height, ~60 m radius
 *   200 mm ≈ 4.2 s rise, ~220 m burst height, ~80 m radius
 * minAudienceDistanceM follows the 0.84 m-per-mm-of-caliber rule the Catalog
 * enforces. Loudness at 15 m: salutes ~148–155 dB, peonies/chrys ~115–125,
 * crossettes ~110, comets/mines ~84–105. Entries quiet enough for the quiet
 * show variant carry the 'low-noise' tag.
 */

import type { PyroEffect } from '../../contracts.js'

export const PYRO_EFFECTS: readonly PyroEffect[] = [
  // ---- peonies -----------------------------------------------------------
  {
    id: 'peony-75-red',
    name: 'Red Peony 75',
    medium: 'pyro',
    tags: ['red', 'shell', 'classic'],
    noiseDbAt15m: 120,
    durationSec: 1.8,
    category: 'peony',
    caliberMm: 75,
    riseTimeSec: 2.2,
    burstHeightM: 90,
    burstRadiusM: 35,
    starCount: 80,
    colors: ['#ff2a2a'],
    dragK: 1.4,
    gravityBias: 0.15,
    minAudienceDistanceM: 65,
  },
  {
    id: 'peony-75-blue',
    name: 'Blue Peony 75',
    medium: 'pyro',
    tags: ['blue', 'shell', 'classic'],
    noiseDbAt15m: 118,
    durationSec: 1.8,
    category: 'peony',
    caliberMm: 75,
    riseTimeSec: 2.2,
    burstHeightM: 90,
    burstRadiusM: 35,
    starCount: 80,
    colors: ['#3355ff'],
    dragK: 1.4,
    gravityBias: 0.15,
    minAudienceDistanceM: 65,
  },
  {
    id: 'peony-100-white',
    name: 'White Peony 100',
    medium: 'pyro',
    tags: ['white', 'shell', 'classic'],
    noiseDbAt15m: 121,
    durationSec: 2.2,
    category: 'peony',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 45,
    starCount: 110,
    colors: ['#ffffff'],
    dragK: 1.3,
    gravityBias: 0.15,
    minAudienceDistanceM: 90,
  },
  {
    id: 'peony-150-gold',
    name: 'Gold Peony 150',
    medium: 'pyro',
    tags: ['gold', 'shell', 'finale'],
    noiseDbAt15m: 123,
    durationSec: 2.6,
    category: 'peony',
    caliberMm: 150,
    riseTimeSec: 3.6,
    burstHeightM: 170,
    burstRadiusM: 60,
    starCount: 160,
    colors: ['#ffc84d'],
    dragK: 1.2,
    gravityBias: 0.15,
    minAudienceDistanceM: 130,
  },

  // ---- chrysanthemums (trailing stars) ------------------------------------
  {
    id: 'chrysanthemum-100-gold',
    name: 'Gold Chrysanthemum 100',
    medium: 'pyro',
    tags: ['gold', 'shell', 'trail'],
    noiseDbAt15m: 122,
    durationSec: 2.8,
    category: 'chrysanthemum',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 45,
    starCount: 120,
    colors: ['#ffb347', '#ffd98a'],
    dragK: 1.1,
    gravityBias: 0.3,
    minAudienceDistanceM: 90,
  },
  {
    id: 'chrysanthemum-150-silver',
    name: 'Silver Chrysanthemum 150',
    medium: 'pyro',
    tags: ['silver', 'shell', 'trail'],
    noiseDbAt15m: 124,
    durationSec: 3.2,
    category: 'chrysanthemum',
    caliberMm: 150,
    riseTimeSec: 3.6,
    burstHeightM: 170,
    burstRadiusM: 60,
    starCount: 170,
    colors: ['#e8eef2', '#c9d4dc'],
    dragK: 1.0,
    gravityBias: 0.3,
    minAudienceDistanceM: 130,
  },

  // ---- willows / brocade (drooping, long-hang) -----------------------------
  {
    id: 'willow-150-gold',
    name: 'Golden Willow 150',
    medium: 'pyro',
    tags: ['gold', 'shell', 'droop'],
    noiseDbAt15m: 119,
    durationSec: 6.5,
    category: 'willow',
    caliberMm: 150,
    riseTimeSec: 3.6,
    burstHeightM: 170,
    burstRadiusM: 55,
    starCount: 140,
    colors: ['#ffd27a'],
    dragK: 0.35,
    gravityBias: 1.0,
    minAudienceDistanceM: 130,
  },
  {
    id: 'brocade-200-gold',
    name: 'Gold Brocade Crown 200',
    medium: 'pyro',
    tags: ['gold', 'shell', 'finale', 'twinkle'],
    noiseDbAt15m: 122,
    durationSec: 7.0,
    category: 'brocade',
    caliberMm: 200,
    riseTimeSec: 4.2,
    burstHeightM: 220,
    burstRadiusM: 80,
    starCount: 220,
    colors: ['#ffcf70', '#fff2c8'],
    dragK: 0.45,
    gravityBias: 0.8,
    minAudienceDistanceM: 170,
  },

  // ---- crossettes (splitting stars) ----------------------------------------
  {
    id: 'crossette-100-red',
    name: 'Red Crossette 100',
    medium: 'pyro',
    tags: ['red', 'split'],
    noiseDbAt15m: 112,
    durationSec: 2.4,
    category: 'crossette',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 40,
    starCount: 48,
    colors: ['#ff3b3b'],
    dragK: 1.2,
    gravityBias: 0.3,
    minAudienceDistanceM: 90,
  },
  {
    id: 'crossette-75-silver',
    name: 'Silver Crossette 75',
    medium: 'pyro',
    tags: ['silver', 'split', 'low-noise'],
    noiseDbAt15m: 98,
    durationSec: 2.0,
    category: 'crossette',
    caliberMm: 75,
    riseTimeSec: 2.2,
    burstHeightM: 90,
    burstRadiusM: 32,
    starCount: 36,
    colors: ['#dfe8ee'],
    dragK: 1.3,
    gravityBias: 0.3,
    minAudienceDistanceM: 65,
  },

  // ---- comets (single rising star with tail; quiet) ------------------------
  {
    id: 'comet-30-gold',
    name: 'Gold Comet 30',
    medium: 'pyro',
    tags: ['gold', 'ascent', 'low-noise'],
    noiseDbAt15m: 84,
    durationSec: 1.6,
    category: 'comet',
    caliberMm: 30,
    riseTimeSec: 1.2,
    burstHeightM: 40,
    burstRadiusM: 6,
    starCount: 1,
    colors: ['#ffd27a'],
    dragK: 1.5,
    gravityBias: 0.5,
    minAudienceDistanceM: 30,
  },
  {
    id: 'comet-50-red',
    name: 'Red Comet 50',
    medium: 'pyro',
    tags: ['red', 'ascent', 'low-noise'],
    noiseDbAt15m: 96,
    durationSec: 2.0,
    category: 'comet',
    caliberMm: 50,
    riseTimeSec: 1.8,
    burstHeightM: 65,
    burstRadiusM: 10,
    starCount: 1,
    colors: ['#ff4040'],
    dragK: 1.4,
    gravityBias: 0.5,
    minAudienceDistanceM: 45,
  },

  // ---- mines (ground-fired spray; riseTimeSec is small by design) ----------
  {
    id: 'mine-50-silver',
    name: 'Quiet Silver Mine 50',
    medium: 'pyro',
    tags: ['silver', 'ground', 'low-noise'],
    noiseDbAt15m: 90,
    durationSec: 1.2,
    category: 'mine',
    caliberMm: 50,
    riseTimeSec: 0.2,
    burstHeightM: 25,
    burstRadiusM: 10,
    starCount: 40,
    colors: ['#e6edf2'],
    dragK: 1.6,
    gravityBias: 0.2,
    minAudienceDistanceM: 45,
  },
  {
    id: 'mine-75-red',
    name: 'Red Mine 75',
    medium: 'pyro',
    tags: ['red', 'ground'],
    noiseDbAt15m: 100,
    durationSec: 1.4,
    category: 'mine',
    caliberMm: 75,
    riseTimeSec: 0.25,
    burstHeightM: 35,
    burstRadiusM: 14,
    starCount: 60,
    colors: ['#ff3b3b'],
    dragK: 1.5,
    gravityBias: 0.2,
    minAudienceDistanceM: 65,
  },

  // ---- salutes (report + brief white flash; loudest entries) ---------------
  {
    id: 'salute-100',
    name: 'Salute 100',
    medium: 'pyro',
    tags: ['white', 'report', 'finale'],
    noiseDbAt15m: 150,
    durationSec: 0.3,
    category: 'salute',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 15,
    starCount: 0,
    colors: ['#ffffff'],
    dragK: 2.5,
    gravityBias: 0,
    minAudienceDistanceM: 90,
  },
  {
    id: 'salute-150',
    name: 'Salute 150',
    medium: 'pyro',
    tags: ['white', 'report', 'finale'],
    noiseDbAt15m: 154,
    durationSec: 0.3,
    category: 'salute',
    caliberMm: 150,
    riseTimeSec: 3.6,
    burstHeightM: 170,
    burstRadiusM: 20,
    starCount: 0,
    colors: ['#ffffff'],
    dragK: 2.5,
    gravityBias: 0,
    minAudienceDistanceM: 130,
  },

  // ---- appended entries (append-only: golden fixtures depend on order) -----
  {
    id: 'peony-75-green',
    name: 'Green Peony 75',
    medium: 'pyro',
    tags: ['green', 'shell', 'classic'],
    noiseDbAt15m: 118,
    durationSec: 1.8,
    category: 'peony',
    caliberMm: 75,
    riseTimeSec: 2.2,
    burstHeightM: 90,
    burstRadiusM: 35,
    starCount: 80,
    colors: ['#3bff7a'],
    dragK: 1.4,
    gravityBias: 0.15,
    minAudienceDistanceM: 65,
  },
  {
    id: 'peony-100-violet',
    name: 'Violet Peony 100',
    medium: 'pyro',
    tags: ['violet', 'shell', 'classic'],
    noiseDbAt15m: 121,
    durationSec: 2.2,
    category: 'peony',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 45,
    starCount: 110,
    colors: ['#8f4dff'],
    dragK: 1.3,
    gravityBias: 0.15,
    minAudienceDistanceM: 90,
  },
  {
    id: 'crossette-100-orange',
    name: 'Orange Crossette 100',
    medium: 'pyro',
    tags: ['orange', 'split'],
    noiseDbAt15m: 112,
    durationSec: 2.4,
    category: 'crossette',
    caliberMm: 100,
    riseTimeSec: 2.8,
    burstHeightM: 120,
    burstRadiusM: 40,
    starCount: 48,
    colors: ['#ff7a1a'],
    dragK: 1.2,
    gravityBias: 0.3,
    minAudienceDistanceM: 90,
  },
  {
    id: 'mine-50-green',
    name: 'Green Mine 50',
    medium: 'pyro',
    tags: ['green', 'ground', 'low-noise'],
    noiseDbAt15m: 88,
    durationSec: 1.2,
    category: 'mine',
    caliberMm: 50,
    riseTimeSec: 0.2,
    burstHeightM: 25,
    burstRadiusM: 10,
    starCount: 40,
    colors: ['#59ff9c'],
    dragK: 1.6,
    gravityBias: 0.2,
    minAudienceDistanceM: 45,
  },
  {
    id: 'comet-30-silver',
    name: 'Silver Comet 30',
    medium: 'pyro',
    tags: ['silver', 'ascent', 'low-noise'],
    noiseDbAt15m: 84,
    durationSec: 1.6,
    category: 'comet',
    caliberMm: 30,
    riseTimeSec: 1.2,
    burstHeightM: 40,
    burstRadiusM: 6,
    starCount: 1,
    colors: ['#dfe8ee'],
    dragK: 1.5,
    gravityBias: 0.5,
    minAudienceDistanceM: 30,
  },
  {
    id: 'willow-150-strobe',
    name: 'Strobing Willow 150',
    medium: 'pyro',
    tags: ['white', 'gold', 'shell', 'droop', 'twinkle'],
    noiseDbAt15m: 119,
    durationSec: 8,
    category: 'willow',
    caliberMm: 150,
    riseTimeSec: 3.6,
    burstHeightM: 170,
    burstRadiusM: 55,
    starCount: 140,
    colors: ['#ffffff', '#ffd27a'],
    dragK: 0.35,
    gravityBias: 1.0,
    minAudienceDistanceM: 130,
  },
  {
    id: 'brocade-200-ice',
    name: 'Ice Brocade Crown 200',
    medium: 'pyro',
    tags: ['white', 'silver', 'shell', 'finale', 'twinkle'],
    noiseDbAt15m: 122,
    durationSec: 7.0,
    category: 'brocade',
    caliberMm: 200,
    riseTimeSec: 4.2,
    burstHeightM: 220,
    burstRadiusM: 80,
    starCount: 220,
    colors: ['#e8f4ff', '#ffffff'],
    dragK: 0.45,
    gravityBias: 0.8,
    minAudienceDistanceM: 170,
  },
]
